Fixed api check script for prod

diff --git a/scripts/lightning-api b/scripts/lightning-api
--- a/scripts/lightning-api
+++ b/scripts/lightning-api
@@ -1,2 +1,20 @@
 #!/usr/bin/env bash
-curl -X 'GET' 'http://localhost:3001/v1/getinfo' -H 'accept: application/json' -H "macaroon: $(xxd -ps -u -c 100 shares/lightning-api-certs/access.macaroon | tr '\n' '\0')" -H 'encodingtype: hex'
+
+if [ $# -eq 0 ]
+  then
+    echo "Rune parameter missing."
+    echo
+    echo "Use the following command to create a rune:"
+    echo
+    echo "./scripts/lightning-cli createrune"
+    echo
+    echo "Currently available runes (showrunes output):"
+    echo
+    source $(dirname "$0")/lightning-cli showrunes --human-readable --filter='{"runes":[{"rune":true}]}'
+    exit 1
+fi
+
+docker run --rm --network bitcoin-main curlimages/curl -s -X 'POST' \
+  'http://10.0.0.3:3001/v1/getinfo' \
+  -H 'accept: application/json' \
+  -H "Rune: $1"
